export const ENDPOINTS = {
  programs: '/programs',
  program: (id: string) => `/programs/${id}`,
  targets: '/targets',
  target: (id: string) => `/targets/${id}`,
  targetStart: (id: string) => `/targets/${id}/start`,
  targetPause: (id: string) => `/targets/${id}/pause`,
  targetResume: (id: string) => `/targets/${id}/resume`,
  approvals: '/approvals',
  approval: (id: string) => `/approvals/${id}`,
  approvalApprove: (id: string) => `/approvals/${id}/approve`,
  approvalDeny: (id: string) => `/approvals/${id}/deny`,
  approvalQueue: '/approvals/queue',
  plugins: '/plugins',
  plugin: (name: string) => `/plugins/${name}`,
  pluginRun: (name: string) => `/plugins/${name}/run`,
  flows: '/flows',
  flow: (id: string) => `/flows/${id}`,
  targetFlows: (targetId: string) => `/flows/target/${targetId}`,
  flowDag: (targetId: string) => `/flows/target/${targetId}/dag`,
  coverage: (targetId: string) => `/coverage/${targetId}`,
}
