# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: credential.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'credential.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63redential.proto\x12\tbugbounty\"Q\n\x14GetCredentialRequest\x12\x15\n\rcredential_id\x18\x01 \x01(\t\x12\x11\n\ttarget_id\x18\x02 \x01(\t\x12\x0f\n\x07purpose\x18\x03 \x01(\t\"v\n\x15GetCredentialResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12)\n\ncredential\x18\x03 \x01(\x0b\x32\x15.bugbounty.Credential\x12\x12\n\nexpires_at\x18\x04 \x01(\x03\"\xd2\x01\n\nCredential\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x05 \x01(\t\x12\r\n\x05token\x18\x06 \x01(\t\x12\x35\n\x08metadata\x18\x07 \x03(\x0b\x32#.bugbounty.Credential.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"2\n\x19ValidateCredentialRequest\x12\x15\n\rcredential_id\x18\x01 \x01(\t\"N\n\x1aValidateCredentialResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x12\n\nexpires_at\x18\x03 \x01(\x03\"1\n\x18RefreshCredentialRequest\x12\x15\n\rcredential_id\x18\x01 \x01(\t\"S\n\x19RefreshCredentialResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x16\n\x0enew_expires_at\x18\x03 \x01(\x03\"\x14\n\x12HealthCheckRequest\"7\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t2\xf8\x02\n\x11\x43redentialService\x12R\n\rGetCredential\x12\x1f.bugbounty.GetCredentialRequest\x1a .bugbounty.GetCredentialResponse\x12\x61\n\x12ValidateCredential\x12$.bugbounty.ValidateCredentialRequest\x1a%.bugbounty.ValidateCredentialResponse\x12^\n\x11RefreshCredential\x12#.bugbounty.RefreshCredentialRequest\x1a$.bugbounty.RefreshCredentialResponse\x12L\n\x0bHealthCheck\x12\x1d.bugbounty.HealthCheckRequest\x1a\x1e.bugbounty.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'credential_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREDENTIAL_METADATAENTRY']._loaded_options = None
  _globals['_CREDENTIAL_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_GETCREDENTIALREQUEST']._serialized_start=31
  _globals['_GETCREDENTIALREQUEST']._serialized_end=112
  _globals['_GETCREDENTIALRESPONSE']._serialized_start=114
  _globals['_GETCREDENTIALRESPONSE']._serialized_end=232
  _globals['_CREDENTIAL']._serialized_start=235
  _globals['_CREDENTIAL']._serialized_end=445
  _globals['_CREDENTIAL_METADATAENTRY']._serialized_start=398
  _globals['_CREDENTIAL_METADATAENTRY']._serialized_end=445
  _globals['_VALIDATECREDENTIALREQUEST']._serialized_start=447
  _globals['_VALIDATECREDENTIALREQUEST']._serialized_end=497
  _globals['_VALIDATECREDENTIALRESPONSE']._serialized_start=499
  _globals['_VALIDATECREDENTIALRESPONSE']._serialized_end=577
  _globals['_REFRESHCREDENTIALREQUEST']._serialized_start=579
  _globals['_REFRESHCREDENTIALREQUEST']._serialized_end=628
  _globals['_REFRESHCREDENTIALRESPONSE']._serialized_start=630
  _globals['_REFRESHCREDENTIALRESPONSE']._serialized_end=713
  _globals['_HEALTHCHECKREQUEST']._serialized_start=715
  _globals['_HEALTHCHECKREQUEST']._serialized_end=735
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=737
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=792
  _globals['_CREDENTIALSERVICE']._serialized_start=795
  _globals['_CREDENTIALSERVICE']._serialized_end=1171
# @@protoc_insertion_point(module_scope)
