# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import credential_pb2 as credential__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in credential_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CredentialServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCredential = channel.unary_unary(
                '/bugbounty.CredentialService/GetCredential',
                request_serializer=credential__pb2.GetCredentialRequest.SerializeToString,
                response_deserializer=credential__pb2.GetCredentialResponse.FromString,
                _registered_method=True)
        self.ValidateCredential = channel.unary_unary(
                '/bugbounty.CredentialService/ValidateCredential',
                request_serializer=credential__pb2.ValidateCredentialRequest.SerializeToString,
                response_deserializer=credential__pb2.ValidateCredentialResponse.FromString,
                _registered_method=True)
        self.RefreshCredential = channel.unary_unary(
                '/bugbounty.CredentialService/RefreshCredential',
                request_serializer=credential__pb2.RefreshCredentialRequest.SerializeToString,
                response_deserializer=credential__pb2.RefreshCredentialResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/bugbounty.CredentialService/HealthCheck',
                request_serializer=credential__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=credential__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class CredentialServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CredentialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredential,
                    request_deserializer=credential__pb2.GetCredentialRequest.FromString,
                    response_serializer=credential__pb2.GetCredentialResponse.SerializeToString,
            ),
            'ValidateCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateCredential,
                    request_deserializer=credential__pb2.ValidateCredentialRequest.FromString,
                    response_serializer=credential__pb2.ValidateCredentialResponse.SerializeToString,
            ),
            'RefreshCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshCredential,
                    request_deserializer=credential__pb2.RefreshCredentialRequest.FromString,
                    response_serializer=credential__pb2.RefreshCredentialResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=credential__pb2.HealthCheckRequest.FromString,
                    response_serializer=credential__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bugbounty.CredentialService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bugbounty.CredentialService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CredentialService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bugbounty.CredentialService/GetCredential',
            credential__pb2.GetCredentialRequest.SerializeToString,
            credential__pb2.GetCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bugbounty.CredentialService/ValidateCredential',
            credential__pb2.ValidateCredentialRequest.SerializeToString,
            credential__pb2.ValidateCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bugbounty.CredentialService/RefreshCredential',
            credential__pb2.RefreshCredentialRequest.SerializeToString,
            credential__pb2.RefreshCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bugbounty.CredentialService/HealthCheck',
            credential__pb2.HealthCheckRequest.SerializeToString,
            credential__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
